/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'field-notes': FieldNote;
    films: Film;
    articles: Article;
    media: Media;
    temples: Temple;
    'temple-pieces': TemplePiece;
    occasions: Occasion;
    drawings: Drawing;
    observances: Observance;
    books: Book;
    users: User;
    regions: Region;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    temples: {
      pieces: 'temple-pieces';
      yearSoFar: 'occasions';
      drawings: 'drawings';
      fieldNotes: 'field-notes';
      articles: 'articles';
    };
  };
  collectionsSelect: {
    'field-notes': FieldNotesSelect<false> | FieldNotesSelect<true>;
    films: FilmsSelect<false> | FilmsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    temples: TemplesSelect<false> | TemplesSelect<true>;
    'temple-pieces': TemplePiecesSelect<false> | TemplePiecesSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    drawings: DrawingsSelect<false> | DrawingsSelect<true>;
    observances: ObservancesSelect<false> | ObservancesSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'about-page': AboutPage;
    instagram: Instagram;
    'section-descriptions': SectionDescription;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    instagram: InstagramSelect<false> | InstagramSelect<true>;
    'section-descriptions': SectionDescriptionsSelect<false> | SectionDescriptionsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Everything recorded at the temples: what happened, in words, photographs and videos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-notes".
 */
export interface FieldNote {
  id: number;
  title: string;
  date: string;
  occasion: string;
  /**
   * Type a name and press Enter. Add as many as needed.
   */
  authors: string[];
  /**
   * Every temple this is about. It will appear on each of their pages.
   */
  temples?: (number | Temple)[] | null;
  /**
   * Every festival or ritual this is about. It will appear on each of their pages.
   */
  observances?: (number | Observance)[] | null;
  /**
   * Write here, or paste from Word or Google Docs. To put a photo or video in the middle of the text: + → Upload.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Drag photos in — several at once is fine. They are shown together after the text.
   */
  photos?: (number | Media)[] | null;
  /**
   * Drag video (or audio) files in. Each plays on the note, with its caption.
   */
  videos?: (number | Media)[] | null;
  /**
   * For the reviewers: what was removed when this was edited from the running log. Never shown.
   */
  removed?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  kind?: ('note' | 'interview' | 'video' | 'audio' | 'photos') | null;
  recording?: (number | null) | Media;
  poster?: (number | null) | Media;
  recordingCaption?: string | null;
  instagram?: {
    postId?: string | null;
    link?: string | null;
  };
  /**
   * Made from the title when left empty. Change it only before publishing.
   */
  slug?: string | null;
  region: number | Region;
  review?: {
    /**
     * For the team's tracking only. Never shown on the site.
     */
    status?: ('awaiting' | 'approved') | null;
    note?: string | null;
  };
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The temples being documented, in the order the site shows them — drag to reorder. Open a temple to edit everything on its page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temples".
 */
export interface Temple {
  id: number;
  _order?: string | null;
  name: string;
  knownAs?: string | null;
  deity: string;
  deityGroup: 'shiva' | 'vishnu' | 'amman' | 'vinayaka' | 'murugan';
  street?: string | null;
  /**
   * A few paragraphs, shown at the top of the temple’s page.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For a future town map. Optional.
   */
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  pieces?: {
    docs?: (number | TemplePiece)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  yearSoFar?: {
    docs?: (number | Occasion)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  drawings?: {
    docs?: (number | Drawing)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  fieldNotes?: {
    docs?: (number | FieldNote)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  articles?: {
    docs?: (number | Article)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Made from the title when left empty. Change it only before publishing.
   */
  slug?: string | null;
  region: number | Region;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Short finished pieces for the "The temple" and "The people" sections of temple pages, polished from the field notes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temple-pieces".
 */
export interface TemplePiece {
  id: number;
  /**
   * For people, their role: "The Bhattars", "The vahana keeper".
   */
  title: string;
  topic: 'temple' | 'people';
  /**
   * It appears on the page of every temple chosen here.
   */
  temples?: (number | Temple)[] | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. A photo or drawing shown above the text.
   */
  picture?: (number | null) | Media;
  /**
   * People are described by their role. Give a name only with their consent.
   */
  named?: {
    name?: string | null;
    /**
     * When and how they agreed to be named. Never shown.
     */
    consent?: string | null;
  };
  /**
   * For the editors checking it. Not shown on the site.
   */
  sources?: (number | FieldNote)[] | null;
  region: number | Region;
  review?: {
    /**
     * For the team's tracking only. Never shown on the site.
     */
    status?: ('awaiting' | 'approved') | null;
    note?: string | null;
  };
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every photo, video, recording and document. Drag several files in at once to upload them together.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * A few words describing the photo, for people who cannot see it.
   */
  alt?: string | null;
  caption?: string | null;
  credit?: string | null;
  /**
   * The picture shown before the video plays. Optional.
   */
  poster?: (number | null) | Media;
  /**
   * Photos, videos and recordings of people need their consent.
   */
  consent: 'not-needed' | 'given' | 'withhold';
  /**
   * Optional. Helps find files later.
   */
  temples?: (number | Temple)[] | null;
  createdBy?: (number | null) | User;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Everyone who can sign in. Admins add people here and choose what they can do.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'contributor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The towns the project documents. Only Pondicherry for now.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  name: string;
  /**
   * Shown at the top of the Temples page.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  totalTemples?: number | null;
  /**
   * The local calendar dates are labelled in.
   */
  calendar: 'tamil';
  /**
   * Made from the title when left empty. Change it only before publishing.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every occasion the team was present for. These make each temple's 'year so far', and the 'where we've seen it' list on festival pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  date: string;
  temple: number | Temple;
  label: string;
  /**
   * The festivals and rituals it involved.
   */
  observances?: (number | Observance)[] | null;
  /**
   * Optional. Linked from the year so far.
   */
  fieldNote?: (number | null) | FieldNote;
  region: number | Region;
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each festival or ritual is explained once. Its page then gathers every temple, date, field note and article tagged with it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "observances".
 */
export interface Observance {
  id: number;
  name: string;
  /**
   * Shown large at the top of the page.
   */
  tamil?: string | null;
  kind: 'festival' | 'ritual';
  alsoKnownAs?: string | null;
  gloss: string;
  /**
   * Questions and answers, in order: "What is it?", "When does it happen?", "What happens?", "What to look for", "In Pondicherry"…
   */
  about?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Made from the title when left empty. Change it only before publishing.
   */
  slug?: string | null;
  review?: {
    /**
     * For the team's tracking only. Never shown on the site.
     */
    status?: ('awaiting' | 'approved') | null;
    note?: string | null;
  };
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Abishek's drawings: each temple's illustrated plan, and scenes photographs can't capture. A drawing appears at the top of every temple and festival page it is tagged with.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drawings".
 */
export interface Drawing {
  id: number;
  title: string;
  /**
   * A temple's plan is shown first on its page.
   */
  kind: 'plan' | 'scene';
  /**
   * Upload the drawing as a large JPG or PNG.
   */
  image: number | Media;
  caption?: string | null;
  credit?: string | null;
  /**
   * Every temple this is about. It will appear on each of their pages.
   */
  temples?: (number | Temple)[] | null;
  /**
   * Every festival or ritual this is about. It will appear on each of their pages.
   */
  observances?: (number | Observance)[] | null;
  region: number | Region;
  review?: {
    /**
     * For the team's tracking only. Never shown on the site.
     */
    status?: ('awaiting' | 'approved') | null;
    note?: string | null;
  };
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Essays and finished pieces. Tag a temple or festival only if the article actually discusses it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  author: string;
  date: string;
  /**
   * One or two sentences shown in lists.
   */
  teaser: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Every temple this is about. It will appear on each of their pages.
   */
  temples?: (number | Temple)[] | null;
  /**
   * Every festival or ritual this is about. It will appear on each of their pages.
   */
  observances?: (number | Observance)[] | null;
  /**
   * Made from the title when left empty. Change it only before publishing.
   */
  slug?: string | null;
  review?: {
    /**
     * For the team's tracking only. Never shown on the site.
     */
    status?: ('awaiting' | 'approved') | null;
    note?: string | null;
  };
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Finished short films, such as the Centre’s Instagram reels. New Instagram posts arrive here as drafts every morning.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films".
 */
export interface Film {
  id: number;
  title: string;
  date: string;
  madeBy?: string | null;
  /**
   * The film itself. Give it a still frame in its own settings, if you like.
   */
  video: number | Media;
  /**
   * Every temple this is about. It will appear on each of their pages.
   */
  temples?: (number | Temple)[] | null;
  /**
   * Every festival or ritual this is about. It will appear on each of their pages.
   */
  observances?: (number | Observance)[] | null;
  /**
   * Shown beside the film. For Instagram films, the original caption.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  instagram?: {
    postId?: string | null;
    link?: string | null;
  };
  /**
   * Made from the title when left empty. Change it only before publishing.
   */
  slug?: string | null;
  region: number | Region;
  review?: {
    /**
     * For the team's tracking only. Never shown on the site.
     */
    status?: ('awaiting' | 'approved') | null;
    note?: string | null;
  };
  createdBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The outline shown on The Book page. It will change as the writing does.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  status: string;
  byline: string;
  illustrations?: string | null;
  parts?:
    | {
        title: string;
        summary: string;
        /**
         * Optional: a link to where the site already covers this part.
         */
        link?: {
          label?: string | null;
          href?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  region: number | Region;
  review?: {
    /**
     * For the team's tracking only. Never shown on the site.
     */
    status?: ('awaiting' | 'approved') | null;
    note?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'field-notes';
        value: number | FieldNote;
      } | null)
    | ({
        relationTo: 'films';
        value: number | Film;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'temples';
        value: number | Temple;
      } | null)
    | ({
        relationTo: 'temple-pieces';
        value: number | TemplePiece;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'drawings';
        value: number | Drawing;
      } | null)
    | ({
        relationTo: 'observances';
        value: number | Observance;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "field-notes_select".
 */
export interface FieldNotesSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  occasion?: T;
  authors?: T;
  temples?: T;
  observances?: T;
  body?: T;
  photos?: T;
  videos?: T;
  removed?:
    | T
    | {
        item?: T;
        id?: T;
      };
  kind?: T;
  recording?: T;
  poster?: T;
  recordingCaption?: T;
  instagram?:
    | T
    | {
        postId?: T;
        link?: T;
      };
  slug?: T;
  region?: T;
  review?:
    | T
    | {
        status?: T;
        note?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "films_select".
 */
export interface FilmsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  madeBy?: T;
  video?: T;
  temples?: T;
  observances?: T;
  body?: T;
  instagram?:
    | T
    | {
        postId?: T;
        link?: T;
      };
  slug?: T;
  region?: T;
  review?:
    | T
    | {
        status?: T;
        note?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  date?: T;
  teaser?: T;
  body?: T;
  temples?: T;
  observances?: T;
  slug?: T;
  review?:
    | T
    | {
        status?: T;
        note?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  poster?: T;
  consent?: T;
  temples?: T;
  createdBy?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temples_select".
 */
export interface TemplesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  knownAs?: T;
  deity?: T;
  deityGroup?: T;
  street?: T;
  intro?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  pieces?: T;
  yearSoFar?: T;
  drawings?: T;
  fieldNotes?: T;
  articles?: T;
  slug?: T;
  region?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "temple-pieces_select".
 */
export interface TemplePiecesSelect<T extends boolean = true> {
  title?: T;
  topic?: T;
  temples?: T;
  body?: T;
  picture?: T;
  named?:
    | T
    | {
        name?: T;
        consent?: T;
      };
  sources?: T;
  region?: T;
  review?:
    | T
    | {
        status?: T;
        note?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  date?: T;
  temple?: T;
  label?: T;
  observances?: T;
  fieldNote?: T;
  region?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "drawings_select".
 */
export interface DrawingsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  image?: T;
  caption?: T;
  credit?: T;
  temples?: T;
  observances?: T;
  region?: T;
  review?:
    | T
    | {
        status?: T;
        note?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "observances_select".
 */
export interface ObservancesSelect<T extends boolean = true> {
  name?: T;
  tamil?: T;
  kind?: T;
  alsoKnownAs?: T;
  gloss?: T;
  about?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  slug?: T;
  review?:
    | T
    | {
        status?: T;
        note?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  byline?: T;
  illustrations?: T;
  parts?:
    | T
    | {
        title?: T;
        summary?: T;
        link?:
          | T
          | {
              label?: T;
              href?: T;
            };
        id?: T;
      };
  region?: T;
  review?:
    | T
    | {
        status?: T;
        note?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  intro?: T;
  totalTemples?: T;
  calendar?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The words on the home page. The newest additions, temples and festivals shown there fill themselves in. "Save" puts changes on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * The large heading.
   */
  headline: string;
  headlineItalic?: boolean | null;
  /**
   * Shown under the heading, beside "Just added". Keep it to two short paragraphs.
   */
  opening?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leave empty for none.
   */
  quoteLabel?: string | null;
  /**
   * Each line here shows on its own line (e.g. the Tamil, then its English). Leave empty to hide the whole band.
   */
  quote?: string | null;
  /**
   * Leave empty for no name.
   */
  quoteBy?: string | null;
  /**
   * Shown below the name, set a little apart.
   */
  quoteAfter?: string | null;
  quoteLinkText?: string | null;
  quoteLink?: string | null;
  bookHeading?: string | null;
  bookText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Everything on the About page. Drag sections to reorder them. "Save" puts changes on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  lede: string;
  /**
   * Each has a heading and its text, shown in this order.
   */
  sections?:
    | {
        heading: string;
        /**
         * Lets other pages link straight here. The home page uses "idea" and "why".
         */
        anchor?: string | null;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  team?:
    | {
        name: string;
        role?: string | null;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  contactText?: string | null;
  contactEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * New Instagram videos arrive every morning as draft films, marked "awaiting review". Nothing appears on the site until someone checks the temples, festivals and consent, and publishes it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram".
 */
export interface Instagram {
  id: number;
  /**
   * From the Meta developer app: Instagram → API setup with Instagram login → Generate access tokens. It lasts 60 days; each import renews it, so it only needs pasting once.
   */
  token?: string | null;
  account?: string | null;
  lastRun?: string | null;
  lastResult?: string | null;
  tokenRenewed?: string | null;
  imported?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The line under the title of each section of the site. "Save" puts changes on the site; an empty box brings back the original.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section-descriptions".
 */
export interface SectionDescription {
  id: number;
  observances?: string | null;
  fieldNotes?: string | null;
  films?: string | null;
  articles?: string | null;
  books?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  headline?: T;
  headlineItalic?: T;
  opening?: T;
  quoteLabel?: T;
  quote?: T;
  quoteBy?: T;
  quoteAfter?: T;
  quoteLinkText?: T;
  quoteLink?: T;
  bookHeading?: T;
  bookText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  lede?: T;
  sections?:
    | T
    | {
        heading?: T;
        anchor?: T;
        body?: T;
        id?: T;
      };
  team?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
        id?: T;
      };
  contactText?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instagram_select".
 */
export interface InstagramSelect<T extends boolean = true> {
  token?: T;
  account?: T;
  lastRun?: T;
  lastResult?: T;
  tokenRenewed?: T;
  imported?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "section-descriptions_select".
 */
export interface SectionDescriptionsSelect<T extends boolean = true> {
  observances?: T;
  fieldNotes?: T;
  films?: T;
  articles?: T;
  books?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}